---
- name: Wait a minute for site to come up
  uri:
    url: '{{ public_protocol }}://{{ http_hostname }}'
    validate_certs: False
  register: site_check
  retries: 11
  delay: 5
  until: site_check.status == 200

- debug:
    msg: 'ERROR {{ site_check.status }} accessing {{ public_protocol }}://{{ http_hostname }}'
  when: site_check.status != 200

- debug:
    msg: '{{ public_protocol }}://{{ http_hostname }} is OK'
  when: site_check.status == 200
