---
- name: Install the certificate and key
  copy:
    src: '{{ certfile_basename }}.key'
    dest: /etc/ssl/private/{{ certfile_basename }}.key
  become: True

- name: Install the certificate and key
  copy:
    src: '{{ certfile_basename }}.crt'
    dest: /etc/ssl/certs/{{ certfile_basename }}.pem
  become: True

- name: Configure Apache SSL Certificate File
  replace:
    path: /etc/apache2/sites-enabled/default-ssl.conf
    regexp: '^\s*SSLCertificateFile.*$'
    replace: 'SSLCertificateFile      /etc/ssl/certs/{{ certfile_basename }}.pem'
  become: True

- name: Configure Apache SSL Certificate Key File
  replace:
    path: /etc/apache2/sites-enabled/default-ssl.conf
    regexp: '^\s*SSLCertificateKeyFile.*$'
    replace: 'SSLCertificateKeyFile /etc/ssl/private/{{ certfile_basename }}.key'
  become: True

- name: Import the public key into the java keystore
  shell: ./refresh-java-keystore.sh
  args:
    chdir: ~/online-whatif/utils
  become: True
