---
- name: Restart all services
  service:
    name: '{{ item }}'
    state: restarted
  with_items:
    - dovecot
    - postfix
    - postgresql
    - couchdb
    - tomcat8
    - apache2
  become: True
