---
- name: Clone whatif
  git:
    repo: '{{ repo_url }}'
    dest: ~/{{ project_name }}

- name: Install whatif
  expect:
    command: /bin/bash ./install.sh
    responses:
      'DNS name to use for whatif .*': '{{ http_hostname }}'
    chdir: '{{ ansible_env.HOME }}/{{ project_name }}/utils'
    timeout:
  become: True
