---
- name: Clone whatif
  git:
    repo: '{{ repo_url }}'
    dest: ~/{{ project_name }}

- name: Install whatif
  expect:
    command: /bin/bash ./install.sh
    responses:
      'DNS name to use for whatif .*': '{{ http_hostname }}'
    chdir: '{{ ansible_env.HOME }}/{{ project_name }}/utils'
    timeout:
  become: True

- include_tasks: config_email.yml

- name: Set admin password
  replace:
    path:
    regexp: '^\s*env.auth.adminPassword\s*=.*$'
    replace: env.auth.adminPassword={{ admin_password }}
  become: True
