---
- name: Install pip and git
  apt:
    name:
      - python-pip
      - git
    update_cache: True
  become: True

- name: Recognise pip3
  alternatives:
    name: pip3
    path: /usr/bin/pip
    link: /usr/bin/pip3
  become: True

- name: Install pexpect for Ansible
  pip:
    name: pexpect
  become: True
