---
- name: Ensure local private key is secure
  file:
    path: '{{ ansible_ssh_private_key_file }}'
    mode: 0600
  delegate_to: localhost

- include_tasks: set_hostname.yml
- name: Configure ssh to use port 443 for github.com
  copy:
    src: ssh_config
    dest: ~/.ssh/config

- include_tasks: set_timezone.yml

- include_tasks: install_requirements.yml
