---
- name: Ensure local private key is secure
  file:
    path: '{{ ansible_ssh_private_key_file }}'
    mode: 0600
  delegate_to: localhost

- include_tasks: set_hostname.yml

- include_tasks: set_timezone.yml

- include_tasks: install_requirements.yml
