---
- name: Ensure local private key is secure
  file:
    path: '{{ ansible_ssh_private_key_file }}'
    mode: 0600
  delegate_to: localhost

- name: Configure ssh to use port 443 for github.com
  copy:
    src: ssh_config
    dest: ~/.ssh/config

- include_tasks:
    file: set_hostname.yml
    apply:
      become: True

- include_tasks:
    file: set_timezone.yml
    apply:
      become: True

- include_tasks:
    file: install_requirements.yml
    apply:
      become: True
